### ISSUE TITLE
chart is missing "the usual" standard labels

### ISSUE THREAD

**Issue by ReSearchITEng** [funkypenguin/helm-kubernetes-dashboard#5]
something like this would be expected in all manifests:
```
  labels:
    app.kubernetes.io/name: {{ template "kubernetes-dashboard.name" . }}
    helm.sh/chart: {{ template "kubernetes-dashboard.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
```
